alias df='df -h'
alias du='du -h'

alias ls='ls --color=auto -h'
alias cls='echo -ne "\033c"'

alias pull="git pull origin"
alias push="git push origin"
alias s="git status"
alias ll="git log"
alias l="git log --pretty=oneline --abbrev-commit --max-count=15"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gdt="git difftool"
alias gmt="git mergetool"
alias co="git checkout"
alias glog="git log --graph --oneline --all"
alias unstage="git reset HEAD"


