New-PSDrive gh filesystem 'c:\work\github'
New-PSDrive gl filesystem 'c:\work\gitlab'
New-PSDrive gf filesystem 'c:\work\42'
New-PSDrive bm filesystem 'c:\work\42\BonMonitor'
New-PSDrive bv filesystem 'c:\work\42\bonviewer_frontend'
New-PSDrive bs filesystem 'c:\work\42\project42bonviewerservice'
