" Settings
" ========================================



" zeigt statuszeile fr einen buffer
set laststatus=2
" gibt die aktuelle cursorposition in der statuszeile an
set ruler
" Keine Backups machen
set nobackup
" dunkler Hintergrund
set background=dark
" Beep Tne abschalten
set noerrorbells
" versteckte Buffer
set hidden
" Zeige Whitespaces
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
" Zeilennummern
set number
"set nonumber
" Folding
set fdm=indent
" visual error
set vb


" Tab wird im Text durchn Leerzeichen mitet te
set tabstop=4
set nowrap
set cursorline
set shiftwidth=4
set autoindent
set fileencoding=utf-8
set encoding=utf-8
"
"--- Vundle ----------------------------
" Vim verhält sich nicht wie Vi
" set nocompatible
" filetype off

" set rtp+=~/.vim/bundle/Vundle.vim
" call vundle#begin()
" vundle manages vundle
" Plugin 'VundleVim/Vundle.vim'

"Utility
" Plugin 'scrooloose/nerdtree'
" Plugin 'matjutsushi/tagbar'
" Plugin 'ervandew/supertab'
" Plugin 'benmills/vimux'
" Plugin 'gilsondev/searchtasks.vim'
" Plugin 'Shougo/neocomplete.vim'

" Generic Programming Support
" Plugin 'tobyS/vmustache'

" Markdown
" Plugin 'tpope/vim-markdown'
" Plugin 'reedes/vim-pencil'

" call vundle#end()

" filetype plugin indent on
"--- Vundle end ---------------------------


" Syntaxhighlighting
"
let color = "true"
"
if has("syntax")
  if color == "true"
    " This will switch colors ON
    so ${VIMRUNTIME}/syntax/syntax.vim
    colorscheme koehler
  else
    " this switches colors OF
    syntax off
    set t_Co=0
  endif
endif
